#!/bin/bash

# adapted from https://askubuntu.com/a/983584

set -x

# 1. Install prerequisites
sudo apt install git cmake ninja-build clang python uuid-dev libicu-dev icu-devtools libbsd-dev libedit-dev libxml2-dev libsqlite3-dev swig libpython-dev libncurses5-dev pkg-config libblocksruntime-dev libcurl4-openssl-dev autoconf libtool systemtap-sdt-dev tzdata

# 2. Download source
mkdir -p /home/eddie/swiftstuff
cd /home/eddie/swiftstuff
git clone https://github.com/apple/swift.git
cd swift
git checkout swift-4.1.1-RELEASE
./utils/update-checkout --clone

# 3. Build source
utils/build-script -R
